### ISSUE TITLE
Problem with the code

### ISSUE THREAD

**Issue by mxgc96** [dweidai/NeuroPy-Python3.0#1]
Hi, I downloaded the library, I have Ubuntu as operating system and Python 3.6.8 and when I run the testing.py file I get this error.

```
headset.stop()

  File ".../NeuroPy-0.1/NeuroPy/NeuroPy.py", line 218, in stop
    if self.__threadRun == True:

AttributeError: 'NeuroPy' object has no attribute '_NeuroPy__threadRun'
```

**Comment by dweidai** [comment]
I updated __threadRun to Running and it should work now
